Repository TryGhost/ActivityPub, pull requests merged in 2025-05, with the labels that each got.

#603 Changed app boot process
  Dockerfile
  boottime.sh
  package.json
  src/app.ts
  src/instrumentation.ts
Labels: ricardo.ghost.is

#629 Revert improve boot time
  Dockerfile
  boottime.sh
  package.json
  src/app.ts
Labels: ricardo-staging-1.ghost.is

#551 Moved Create<Note> creation and publishing to FediverseBridge
  features/create-note.feature
  features/followers.feature
  features/step_definitions/activitypub_steps.js
  features/step_definitions/note_steps.js
  features/support/activitypub.js
  features/support/utils.js
  src/activity-handlers/create.handler.ts
  src/activitypub/__snapshots__/publish-note-create-activity.json
  src/activitypub/__snapshots__/publish-post-create-activity.json
  src/activitypub/fediverse-bridge.ts
  src/activitypub/fediverse-bridge.unit.test.ts
  src/http/api/note.ts
  src/http/api/webhook.ts
  src/publishing/__snapshots__/service/publish-post-create-activity.json
  src/publishing/__snapshots__/service/publish-post-publish-result.json
  src/publishing/helpers.ts
  src/publishing/service.ts
  src/publishing/service.unit.test.ts
  src/publishing/types.ts
Labels: princi-vershwal-12.ghost.is

#656 Added `mentions` table
  migrate/migrations/000050_add-mentions-table.down.sql
  migrate/migrations/000050_add-mentions-table.up.sql
Labels: princi-vershwal-12.ghost.is

#658 Increased key column size on key_value table
  migrate/gh-ost.Dockerfile
  migrate/migrations/000051_alter-key-on-key-value-table.down.sql
  migrate/migrations/000051_alter-key-on-key-value-table.up.sql
Labels: ricardo.ghost.is

#727 Fixed CI/CD staging tests
  .github/workflows/cicd.yml
Labels: ricardo.ghost.is
