Repository TryGhost/ActivityPub, pull requests merged in 2025-04, with the labels that each got.

#432 Added ephemeral staging environments
  .github/workflows/cicd.yml
Labels: ricardo.ghost.is

#533 Added Google Cloud Storage (GCS) integration for image uploads
  .gitignore
  docker-compose.yml
  fake-gcs/Dockerfile
  fake-gcs/start.sh
  features/step_definitions/stepdefs.js
  features/upload-image.feature
  package.json
  src/app.ts
  src/http/api/index.ts
  src/http/api/storage.ts
  src/http/api/storage.unit.test.ts
  src/storage/gcloud-storage/gcp-storage.service.ts
  src/storage/gcloud-storage/gcp-storage.service.unit.test.ts
  yarn.lock
Labels: ricardo.ghost.is, princi-vershwal-12.ghost.is, main.ghost.is, ricardo-staging-1.ghost.is

#558 AP-982 | Attach images to notes/replies
  features/create-note.feature
  features/create-reply.feature
  features/step_definitions/stepdefs.js
  src/app.ts
  src/handlers.ts
  src/http/api/note.ts
  src/post/post.entity.ts
  src/post/post.entity.unit.test.ts
  src/publishing/service.ts
  src/publishing/types.ts
  src/storage/gcloud-storage/gcp-storage.service.ts
  src/storage/gcloud-storage/gcp-storage.service.unit.test.ts
Labels: princi-vershwal-12.ghost.is, main.ghost.is
