Repository TryGhost/ActivityPub, pull requests merged in 2025-07, with the labels that each got.

#990 Refactor controllers
  src/app.ts
  src/configuration/registrations.ts
  src/http/api/account.controller.ts
  src/http/api/block.controller.ts
  src/http/api/derepost.ts
  src/http/api/feed.controller.ts
  src/http/api/feed.unit.test.ts
  src/http/api/follow.controller.ts
  src/http/api/index.ts
  src/http/api/like.controller.ts
  src/http/api/media.controller.ts
  src/http/api/media.controller.unit.test.ts
  src/http/api/note.ts
  src/http/api/notification.controller.ts
  src/http/api/post.controller.ts
  src/http/api/post.controller.unit.test.ts
  src/http/api/post.ts
  src/http/api/reply.ts
  src/http/api/repost.ts
  src/http/api/search.controller.ts
  src/http/api/site.controller.ts
  src/http/api/webfinger.controller.ts
  src/http/api/webfinger.unit.test.ts
  src/http/api/webhook.controller.ts
Labels: apdevstaging.ghost.is

#1018 Cleaned up fediverse bridge unit tests
  src/activitypub/fediverse-bridge.unit.test.ts
Labels: tidying

#1075 Set Ghost (Pro) flag when creating a new site
  docker-compose.yml
  src/configuration/registrations.ts
  src/http/api/site.controller.ts
  src/http/api/site.controller.unit.test.ts
  src/site/site.service.integration.test.ts
  src/site/site.service.ts
Labels: apdevstaging.ghost.is

#1113 Fixed "ghost_pro" flag assignment
  src/http/api/site.controller.ts
  src/http/api/site.controller.unit.test.ts
Labels: sag-site-10.ghost.is

#1120 Extracted KvStroe key serialization into method
  src/knex.kvstore.ts
Labels: tidying
